/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ff8f6f",
        "primary-container": "#ff7851",
        "primary-dim": "#ff734a",
        "primary-fixed": "#ff7851",
        "primary-fixed-dim": "#ff5d2b",
        "on-primary": "#5c1400",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#581300",
        "on-primary-container": "#470e00",
        "error": "#ff716c",
        "error-dim": "#d7383b",
        "error-container": "#9f0519",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
        "surface": "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131313",
        "surface-container": "#1a1a1a",
        "surface-container-high": "#20201f",
        "surface-container-highest": "#262626",
        "surface-variant": "#262626",
        "surface-tint": "#ff8f6f",
        "on-surface": "#ffffff",
        "on-surface-variant": "#adaaaa",
        "background": "#0e0e0e",
        "on-background": "#ffffff",
        "secondary": "#d7e5ec",
        "secondary-container": "#3c494f",
        "secondary-dim": "#c9d7de",
        "secondary-fixed": "#d7e5ec",
        "secondary-fixed-dim": "#c9d7de",
        "on-secondary": "#46545a",
        "on-secondary-container": "#c4d2da",
        "on-secondary-fixed": "#344147",
        "on-secondary-fixed-variant": "#505e64",
        "tertiary": "#f2fbff",
        "tertiary-dim": "#e3ecf0",
        "tertiary-container": "#e3ecf0",
        "tertiary-fixed": "#f2fbff",
        "tertiary-fixed-dim": "#e3ecf0",
        "on-tertiary": "#576064",
        "on-tertiary-container": "#4f585c",
        "on-tertiary-fixed": "#464e52",
        "on-tertiary-fixed-variant": "#626b6f",
        "outline": "#767575",
        "outline-variant": "#484847",
        "inverse-surface": "#fcf9f8",
        "inverse-on-surface": "#565555",
        "inverse-primary": "#b12f00",
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      backdropBlur: {
        "xl": "20px",
      },
      boxShadow: {
        "glow": "0 0 20px rgba(255, 143, 111, 0.3)",
      }
    },
  },
  plugins: [],
}
